version: '3'

services:
  php82-fpm:
    container_name: php82
    hostname: php82
    build:
      context: ./php
      dockerfile: ./82/Dockerfile
      args:
        - EXTRA_CMDS=${EXTRA_CMDS_PHP82}
        - CUSTOM_USER_NAME=${CUSTOM_USER_NAME}
        - CUSTOM_UID=${CUSTOM_UID}
        - CUSTOM_GID=${CUSTOM_GID}
    restart: ${DOCKER_RESTART}
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
    networks:
      lde-network:
    user: ${CUSTOM_UID}:${CUSTOM_GID}
